openapi: "3.0.1"
info:
  title: "eauction-api"
  version: "v0"
servers:
- url: "https://kzjbpinr64.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/prod"
paths:
  /e-auction/api/v1/seller/delete/{productID}:
    delete:
      operationId: "detleteProduct"
      parameters:
      - name: "productID"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "202":
          description: "202 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    options:
      parameters:
      - name: "productID"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "202":
          description: "202 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /e-auction/api/v1/seller/add-product:
    post:
      operationId: "addProduct"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductAuction"
        required: true
      responses:
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "201":
          description: "201 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "201":
          description: "201 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /e-auction/api/v1/seller/show-bids/{productID}:
    get:
      operationId: "getBids"
      parameters:
      - name: "productID"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    options:
      parameters:
      - name: "productID"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /e-auction/api/v1/buyer/place-bid:
    post:
      responses:
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "201":
          description: "201 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    options:
      responses:
        "201":
          description: "201 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /e-auction/api/v1/seller/get-product/{productID}:
    get:
      operationId: "getProduct"
      parameters:
      - name: "productID"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    options:
      parameters:
      - name: "productID"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /e-auction/api/v1/email:
    post:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /e-auction/api/v1/buyer/update-bid/{productId}/{buyerEmailld}/{newBidAmount}:
    put:
      parameters:
      - name: "productId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "newBidAmount"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "buyerEmailld"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    options:
      parameters:
      - name: "productId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "newBidAmount"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "buyerEmailld"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  schemas:
    Address:
      type: "object"
      properties:
        addressLine:
          type: "string"
        city:
          type: "string"
        state:
          type: "string"
        pin:
          type: "string"
    Product:
      required:
      - "productName"
      type: "object"
      properties:
        productID:
          type: "string"
        productName:
          maxLength: 30
          minLength: 5
          type: "string"
        shortDescription:
          type: "string"
        detailedDescription:
          type: "string"
        category:
          type: "string"
    Seller:
      required:
      - "email"
      - "firstName"
      - "lastName"
      - "phone"
      type: "object"
      properties:
        email:
          type: "string"
        firstName:
          maxLength: 30
          minLength: 5
          type: "string"
        lastName:
          maxLength: 25
          minLength: 3
          type: "string"
        address:
          $ref: "#/components/schemas/Address"
        phone:
          maxLength: 10
          minLength: 10
          type: "string"
    ProductAuction:
      required:
      - "startPrice"
      type: "object"
      properties:
        email:
          type: "string"
        productID:
          type: "string"
        seller:
          $ref: "#/components/schemas/Seller"
        product:
          $ref: "#/components/schemas/Product"
        startPrice:
          type: "number"
        bidEndDate:
          type: "string"
          format: "date-time"
